services:
  - type: web
    name: 0ld-youtube
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: 0ld-youtube-db
          property: connectionString
      - key: MAX_FILE_MB
        value: "100"

databases:
  - name: 0ld-youtube-db
    plan: free
    databaseName: oldtube
    user: oldtube